name: earth-analytics-python
channels:
  - conda-forge
dependencies:
  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - contextily
  - pysal
  - pyproj
  - folium
  - gdal
  - geocoder
  - geojson

  # natural language processing
  - tweepy
  - nltk

  - pip:
      # Utilities
      - download
      - nbgrader
      - nbclean
      - mne
      - tqdm
      - mapboxgl
      - git+https://github.com/geopandas/geopandas.git
      - git+https://github.com/earthlab/earthpy.git@af51f956ed17b4d9ebf32623c23a8c0b9f8d265d
